Features/slider
zinuu4/CineBuddy pull request #21
Opened 2023-08-08 14:55 UTC by almalmalm

Add dinamic data to trailers slider. Implement api route.

2023-08-08 16:08 UTC, NurkenInc approved these changes
Looks good to me, but it's better to resolve build fails!

2023-08-09 17:44 UTC, zinuu4 approved these changes
Well done!)

2023-08-09 17:49 UTC, zinuu4 requested changes

2023-08-09 17:49 UTC, zinuu4 commented on src/shared/ui/mute-button/ui.tsx
It's better to unite mute button and volume button into one and change icon inside depending on coming props

2023-08-09 17:49 UTC, zinuu4 commented on src/shared/ui/volume-button/ui.tsx
It's better to unite mute button and volume button into one and change icon inside depending on coming props

2023-08-10 20:13 UTC, almalmalm commented on src/shared/ui/mute-button/ui.tsx
Delete mute button component.

2023-08-10 20:14 UTC, almalmalm commented on src/shared/ui/volume-button/ui.tsx
Add switch volume logic to  volume button component.

2023-08-11 07:37 UTC, zinuu4 approved these changes
Well done!

2023-08-11 07:37 UTC, merged